// src/components/Checkbox.vue
<template>
    <div class="checkbox-wrapper">
      <div class="checkbox" @click="handler" :class="klass"></div>
    </div>
</template>

<script>
export default {
  name: 'Checkbox',
  props: { value: Boolean, disabled: Boolean },
  data () {
    return {
      internalVal: this.value
    };
  },
  methods: {
    handler () {
      if (this.disabled) return;
      this.internalVal = !this.internalVal;
      this.$emit('input', this.internalVal);
    }
  },
  computed: {
    klass () {
      return {
        checked: this.internalVal,
        disabled: this.disabled
      };
    }
  },
  watch: {
    value (nv) {
      this.internalVal = nv;
    }
  }
};
</script>

<style lang="scss" scoped>
  @import '../styles/base';

  .checkbox-wrapper {
    min-width: 1em;
    max-width: 1em;
    min-height: 1em;
    max-height: 1em;
    display: inline-flex;
    justify-content: center;
    align-items: center;

    .checkbox {
      border: $border;
      background: transparent;
      min-width: 0.9em;
      max-width: 0.9em;
      min-height: 0.9em;
      max-height: 0.9em;

      &.checked {
        background: $accent-color;
      }

      &.checked.disabled {
        background: $disabled-color;
      }
    }
  }
</style>

// src/popup/components/Checkbox.tsx
import { useCallback } from "react";
import { styled } from "styled-components";

const CheckboxElement = styled.div<Omit<CheckboxProps, "onChange">>`
  border: 1px solid ${({ theme }) => theme.colors.controlTrack};
  background-color: ${({ disabled, checked, theme }) => disabled ? theme.colors.disabled : checked ? theme.colors.accentPrimary : "transparent"};
  min-width: 12px;
  max-width: 12px;
  min-height: 12px;
  max-height: 12px;
`;

type CheckboxProps = {
  checked: boolean,
  disabled?: boolean,
  onChange: (nv: boolean) => void
};

function Checkbox({
  checked,
  disabled = false,
  onChange
}: CheckboxProps) {
  const handler = useCallback(() => {
    if (disabled) return;
    onChange(!checked);
  }, [checked, disabled, onChange]);

  return (
    <CheckboxElement checked={checked} disabled={disabled} onClick={handler} className="themed controlTrack accentPrimary disabled" />
  );
}

export { Checkbox };
